package components

import (
	"github.com/hexops/vecty"
	"github.com/hexops/vecty/elem"
	"github.com/hexops/vecty/prop"
)

// Footer defines the footer structrue
type Footer struct {
	vecty.Core
}

// Render renders the footer structrue
func (f *Footer) Render() vecty.ComponentOrHTML {
	return elem.Div(
		vecty.Markup(prop.ID("scnace-footer")),
		elem.Footer(
			vecty.Markup(
				vecty.UnsafeHTML(`❤️ Auto-generated By <a href="https://github.com/gopherjs/gopherjs">GopherJS</a> and <a href="https://github.com/hexops/vecty">vecty</a>`),
			),
		),
		elem.Footer(
			vecty.Markup(
				vecty.UnsafeHTML(`📦 Deployed on <a href="https://aws.amazon.com/cn/lambda/">AWS Lambda</a>`),
			),
		),
	)
}
