kind: pipeline
name: homepage

workspace:
  base: /go
  path: src/github.com/scbizu/homepage

steps:
- name: build
  image: golang:1.11
  environment:
    GO111MODULE: on
  commands:
  - go install
- name: up_dev
  image: golang:1.11
  environment:
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    GO111MODULE: on
  commands:
  - curl -sf https://up.apex.sh/install | sh
  - up deploy staging
  when:
    event:
    - push
    - pull_request
    branch:
    - feature/*

- name: up_prod
  image: golang:1.11
  environment:
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    GO111MODULE: on
  commands:
  - curl -sf https://up.apex.sh/install | sh
  - up deploy production
  when:
    event:
    - push
    branch:
    - master
