package main

import (
	"github.com/gopherjs/vecty"
	"github.com/gopherjs/vecty/elem"
)

// Homepage defines full view of https://scnace.me/
type Homepage struct {
	vecty.Core
}

// Render implements the vecty.Component interface.
func (hp *Homepage) Render() vecty.ComponentOrHTML {
	return elem.Body(
		elem.Paragraph(
			vecty.Text("This site will stay in maintance in a long-long time,you can find me via telegram @scnace"),
		),
		elem.Footer(
			vecty.Markup(
				vecty.Style("text-align", "center"),
				vecty.Style("position", "absolute"),
				vecty.Style("bottom", "0"),
				vecty.Style("width", "100%"),
				// vecty.Style("height", "100px"),
			),
			vecty.Markup(
				vecty.UnsafeHTML(`❤️ Autogenerated By <a href="https://github.com/gopherjs/gopherjs">GopherJS</a> and <a href="https://github.com/gopherjs/vecty">vecty</a>`),
			),
		),
		vecty.Markup(
			// vecty.Style("height", "100%"),
			vecty.Style("min-height", "100%"),
			vecty.Style("padding", "0"),
			vecty.Style("margin", "0"),
		),
	)
}

func main() {
	vecty.SetTitle("scnace|一只菜鸡的成长之路")
	vecty.RenderBody(&Homepage{})
}
